version: '3.8'

services:
  bitwarden:
    image: vaultwarden/server:latest
    container_name: bitwarden
    restart: always
    ports:
      - 84:80
      - 3014:3014
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
    environment:
      - WEBSOCKET_ENABLED=true
      - SIGNUPS_ALLOWED=true
      - DOMAIN=https://bitwarden.hanisntsolo.online # Replace with your domain name or IP address
      - ROCKET_PORT=3014
    volumes:
      - /docker/bitwarden/bw-data:/data
