version: '3.8'

services:
  rustpad:
    image: hanisntsolo/rustpad:latest
    container_name: rustpad
    restart: always
    ports:
      - "3030:3030"
    volumes:
      - "/media/hanisntsolo/WDBlue_ssd_hanis/docker/volumes/jupyter/notebooks/jupyter-lab/rustpad_db/:/persist"
    environment:
      - EXPIRY_DAYS=365
      - PORT=3030
      - RUST_LOG=OFF #TRACE,OFF,error,warn,info,debug
      - SQLITE_URI=sqlite:///persist/rustpad.db
