version: '3.8'

services:
  mqtt:
    image: eclipse-mosquitto:2.0
    container_name: mqtt_broker
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - "${DOCKER_DATA}/mosquitto/config:/mosquitto/config"
      - "${DOCKER_DATA}/mosquitto/data:/mosquitto/data"
      - "${DOCKER_DATA}/mosquitto/log:/mosquitto/log"
    restart: unless-stopped
    environment:
      - MOSQUITTO_CONFIG=${DOCKER_DATA}/mosquitto/config/mosquitto.conf
