grafana:
    image: grafana/grafana:7.5.7
    container_name: grafana
    ports:
      - 8086:3000
#    deploy:
#      resources:
#        limits:
#          cpus: '1.0'
#          memory: 512M
    restart: always
    volumes:
      - /media/hanisntsolo/WDBlue_ssd_hanis/docker/volumes/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - /media/hanisntsolo/WDBlue_ssd_hanis/docker/volumes/grafana/grafana-data:/var/lib/grafana
