version: '3'

# Create a custom network for the containers to communicate
networks:
  nextcloud_network:

services:

  # Nextcloud service
  nextcloud:
    image: nextcloud
    container_name: nextcloud
    restart: always
    ports:
      - 1080:80
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
    networks:
      - nextcloud_network
    environment:
      - NEXTCLOUD_TRUSTED_DOMAINS=https://nextcloud.hanisntsolo.online
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=${NEXTCLOUD_DB}
      - MYSQL_USER=${NEXTCLOUD_USER}
      - MYSQL_PASSWORD=${NEXTCLOUD_PASSWORD}
    volumes:
      # host drive
      # - nextcloud_data:/var/www/html
      # external ssd 
      - /media/hanisntsolo/WDBlue_ssd_hanis/docker/volumes/nextcloud_nextcloud_data:/var/www/html

  # MySQL database service
  mysql:
    image: mariadb
    container_name: nextcloud_mysql
    restart: always
    networks:
      - nextcloud_network
    environment:
      - MYSQL_ROOT_PASSWORD=${NEXTCLOUD_PASSWORD}
      - MYSQL_DATABASE=${NEXTCLOUD_DB}
      - MYSQL_USER=${NEXTCLOUD_USER}
      - MYSQL_PASSWORD=${NEXTCLOUD_PASSWORD}
    ports:
      - "3312:3306"
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
    volumes:
      # host drive
      - mysql_data:/var/lib/mysql
      # external ssd
      # - /media/hanisntsolo/WDBlue_ssd_hanis/docker/volumes/nextcloud_mysql_data:/var/lib/mysql
volumes:
  # On host drive
  # nextcloud_data:
  mysql_data:
  # On External SSD
  # On host drive
  # nextcloud_data:/media/hanisntsolo/WDBlue_ssd_hanis/docker/volumes/nextcloud_nextcloud_data
  # mysql_data:/media/hanisntsolo/WDBlue_ssd_hanis/docker/volumes/nextcloud_mysql_data
  # On External SSD

  # /media/hanisntsolo/WDBlue_ssd_hanis/docker/volumes/nextcloud_nextcloud_data:/var/www/html
  # /media/hanisntsolo/WDBlue_ssd_hanis/docker/volumes/nextcloud_mysql_data:/var/lib/mysql
