version: '3.3'

services:
  app:
    image: fireflyiii/core:latest
    environment:
      - APP_URL=https://firefly.hanisntsolo.online
      - TRUSTED_PROXIES=**
      - VIRTUAL_HOST=https://firefly.hanisntsolo.com
      - VIRTUAL_PORT=8080
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true"
    hostname: app
    container_name: firefly_iii_core
    restart: always
    volumes:
      - firefly_iii_upload:/var/www/html/storage/upload
    env_file: .env
    networks:
      - firefly_iii
    ports:
      - 7082:8080
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
    depends_on:
      - db
  db:
    image: mysql:8.0.34
    hostname: db
    container_name: firefly_iii_db
    restart: always
    env_file: .db.env
    networks:
      - firefly_iii
    volumes:
      - /media/hanisntsolo/WDBlue_ssd_hanis/docker/volumes/fireflyDBdata:/var/lib/mysql
    ports:
      - 7308:3306
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
  cron:
    #
    # To make this work, set STATIC_CRON_TOKEN in your .env file or as an environment variable and replace REPLACEME below
    # The STATIC_CRON_TOKEN must be *exactly* 32 characters long
    #
    image: alpine
    restart: always
    container_name: firefly_iii_cron
    command: sh -c "echo \"0 3 * * * wget -qO- http://app:7082/api/v1/cron/ZhTIN4aDoQo66uOPxqk8c8jMY9H6AVrE\" | crontab - && crond -f -L /dev/stdout"
    networks:
      - firefly_iii
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M

volumes:
   firefly_iii_upload:

networks:
  firefly_iii:
    driver: bridge
