version: '3.8'

services:
  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle_container
    restart: always
    ports:
      - "8082:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  default:
    external:
      name: npm_default
