FROM debian:latest

RUN apt-get update && apt-get install -y sudo

FROM jenkins/jenkins:lts

# Arguments for specifying UID and GID
ARG USER=jenkins
ARG GROUP=docker
ARG UID=1002
ARG GID=1002

USER root

# Add Docker group with specific GID
RUN groupadd -g 999 docker

# Check the GID of the 'docker' group inside the container
# RUN getent group docker
# Check the GID of the 'docker' group inside the container
# Check the GID of the 'docker' group inside the container
RUN getent group docker || echo "Group 'docker' not found"
# RUN cat /etc/group | grep docker
# Add Jenkins user with specific UID
# RUN useradd -u 1002 -g 999 -ms /bin/bash jenkins
# Install sudo
RUN apt-get update && apt-get install -y sudo

# Install dependencies for Docker
RUN apt-get update && apt-get install -y \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg \
    lsb-release

# Install Docker using official installation script
RUN curl -fsSL https://get.docker.com -o get-docker.sh
RUN sh get-docker.sh

# Add Jenkins user to the Docker group and adjust permissions on Docker socket
# RUN usermod -aG docker jenkins && \ 
  #  chmod 666 /var/run/docker.sock && \ 
  #  chown root:docker /var/run/docker.sock
# Add Jenkins user to the Docker group
RUN groupmod -g 1002 jenkins && usermod -u 1002 -g 1002 jenkins
RUN usermod -aG docker jenkins
RUN chown -R jenkins:jenkins /var/jenkins_home
RUN chmod -R 755 /var/jenkins_home
# RUN groupadd -g 999 docker && usermod -aG docker jenkins
# Ensure Jenkins home directory exists and has correct permissions
RUN mkdir -p /var/jenkins_home && chown -R jenkins:jenkins /var/jenkins_home
# Change the UID and GID of the Jenkins user
# RUN usermod -u ${UID} ${USER} && groupmod -g ${GID} ${GROUP}
# RUN usermod -u 1002 jenkins && groupmod -g 1002 jenkins
# Install Node.js and npm
RUN curl -sL https://deb.nodesource.com/setup_14.x | bash -
RUN apt-get install -y nodejs

USER jenkins
