version: '3'

services:
  app:
    image: jc21/nginx-proxy-manager:latest
    restart: always
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
    environment:
      DB_MYSQL_HOST: db
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: npm
      DB_MYSQL_PASSWORD: npm
      DB_MYSQL_NAME: npm
    volumes:
      - data_volume:/data  # Data directory for Nginx Proxy Manager
      - letsencrypt_volume:/etc/letsencrypt  # Let's Encrypt certificates
    depends_on:
      - db
    networks:
      - npm_default

  db:
    image: jc21/mariadb-aria:latest
    restart: always
    ports:
      - 3304:3306
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
    environment:
      MYSQL_ROOT_PASSWORD: pass.database
      MYSQL_DATABASE: npm
      MYSQL_USER: npm
      MYSQL_PASSWORD: npm
      MARIADB_AUTO_UPGRADE: '1'
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - npm_default

networks:
  npm_default:
    external: true
    driver: bridge
volumes:
  data_volume:
  letsencrypt_volume:
  mysql_data:
